#+TITLE: IGVC Project Plan
* General Information
1. Project Name: IGVC - Intelligent Ground Vehicle Competition
2. Team members:
   - Viet Dung Nguyen (CSE) ([[mailto:dnguyen2016@my.fit.edu][dnguyen2016@my.fit.edu]])
   - Jinwen Zhang ([[mailto:jzhang2015@my.fit.edu][jzhang2015@my.fit.edu]])
   - John Light ([[mailto:jlight2016@my.fit.edu][jlight2016@my.fit.edu]])
   - Sijin Yang ([[mailto:yangs2017@my.fit.edu][yangs2017@my.fit.edu]])
   - Peter Tarsoly ([[mailto:ptarsoly2016@my.fit.edu][ptarsoly2016@my.fit.edu]])
3. Faculty Sponsor: Dr. Marius Silaghi
4. Client: Dr. Ken Gibbs
5. Meetings with the Client:
   - 06/30/2019
* Goal and Motivation
The goal of the project is to build an unmanned autonomous robot to compete in
IGVC in Michigan. The objective of the competition is to have the robot complete
an outdoor obstacle course under a prescribe time within the speed limit of 1-5
mph while remaining on the lane and avoiding obstacles.
* Approach:
The key features of the software components are:
- Lane detection
- Obstacle detection and avoidance
- Mapping
- Motion planning
* Lane detection
The robot must be able to follow the path specified by the competition. The
boundary of this path will be illustrated by dashed or continuous white lines.
Lane detection is necessary for the robot to detect these boundaries.
* Obstacle detection
Within the course, there will be natural and artificial obstacbles. Obstacle
detection and avoidance allow the robot to detect obstacbles and move around
them. This is essential for the robot to complete the course.
* Mapping
Mapping let the robot construct a virtual map of the obstacle course using the
data from lane detection and obstacle detection. With mapping, the robot can
remember the collected data and avoid redundant data collection. In addition,
the robot can remember the where it has been and avoid backtracking.
* Motion planning
Motion planning is a crucial feature of the robot. Using motion planning, the
robot can construct the shortest path to the checkpoints from the data
illustrated in the map. Efficient motion planning is essential for finishing the
course in time.

* Technical Challenges:
- Legacy code is not well documented.
- Motion planning is not implemented
- Team members have no experience with Arduino.
- Team members have no experience with lane and obstacble detection.
* Milestone 1:
- Examine the legacy code in order to reuse.
- Examine the options available for motion planning.
- Establish best practices (code format, document style) for the project.
- Create requirement document
- Create design document
- Create test plan
* Milestone 2:
- Implement automated testing.
- Refactor the legacy code.
- Test for regression.
* Milestone 3:
- Implement and test motion planning.
* Questions?
